export type XianyuInboundEvent =
  | { kind: "ACK" }
  | { kind: "SESSION_SIGNAL"; chatId: string }
  | { kind: "PNM_STATUS"; chatId: string; messageIds: string[] }
  | { kind: "ORDER_CONTEXT"; chatId: string; orderId: string; itemId: string; buyerUserId: string }
  | { kind: "TEXT_MESSAGE"; chatId: string; messageId: string; senderId: string; itemId: string; text: string }
  | { kind: "IMAGE_MESSAGE"; chatId: string; messageId: string; senderId: string; itemId: string; imageUrl: string }
  | { kind: "WAITING_PAYMENT_CARD"; chatId: string; messageId: string; senderId: string; itemId: string; orderId: string }
  | { kind: "PAID_CARD"; chatId: string; messageId: string; senderId: string; itemId: string; orderId: string }
  | { kind: "PAYMENT_SUMMARY"; chatId: string; redReminder: "等待卖家发货" }
  | { kind: "WAITING_PAYMENT_SUMMARY"; chatId: string; redReminder: "等待买家付款" }
  | { kind: "MESSAGE_UPDATE"; chatId: string; messageId: string; orderId: string; updateType: "TRADE_MODIFY_FEE_BUYER" }
  | { kind: "IGNORED_TIP_MESSAGE"; chatId: string; messageId: string };

type RecordValue = Record<string, unknown>;
type Identity = { chatId: string; messageId: string; senderId: string; itemId: string };
type CommonMetadata = Identity & { taskId: string; extJson: RecordValue };

const ordinaryMetadataKeys = ["_appVersion", "_platform", "bizTag", "clientIp", "detailNotice", "extJson", "port", "reminderContent", "reminderNotice", "reminderTitle", "reminderUrl", "senderUserId", "senderUserType", "sessionType", "umid", "umidToken", "utdid"];
const cardMetadataBase = ["bizTag", "closePushReceiver", "closeUnreadNumber", "detailNotice", "extJson", "receiver", "redReminder", "redReminderStyle", "reminderContent", "reminderNotice", "reminderTitle", "reminderUrl", "senderUserId", "senderUserType", "sessionType", "updateHead"];
const tipMetadataKeys = ["bizTag", "closePushReceiver", "closeUnreadNumber", "detailNotice", "extJson", "receiver", "reminderContent", "reminderNotice", "reminderTitle", "reminderUrl", "senderUserId", "senderUserType", "sessionType", "updateHead"];
const multiChannelKeys = ["huawei", "xiaomi", "oppo_notify_level", "honor", "agoo", "oppo_category", "vivo"];
const taskTagKeys = ["sourceId", "taskName", "materialId", "taskId"];

export function decodeXianyuPayload(value: unknown): XianyuInboundEvent {
  const payload = requireRecord(value, "xianyu payload");
  if (Object.hasOwn(payload, "code")) return decodeAck(payload);
  if (Object.keys(payload).length === 1 && Array.isArray(payload["1"])) return decodeSessionSignal(payload);
  if (isStandard(payload)) return decodeStandard(payload);
  if (isMessageUpdate(payload)) return decodeMessageUpdate(payload);
  if (isPnm(payload)) return decodePnm(payload);
  if (isOrderContext(payload)) return decodeOrderContext(payload);
  if (isSummary(payload)) return decodeSummary(payload);
  throw new Error("unknown xianyu payload shape");
}

function decodeAck(payload: RecordValue): XianyuInboundEvent {
  exactKeys(payload, ["headers", "code"], "ACK");
  literal(payload.code, 200, "ACK code");
  const headers = requireRecord(payload.headers, "ACK headers");
  const keys = Object.keys(headers).sort().join(",");
  if (keys === "mid,server-timestamp") {
    nonEmpty(headers.mid, "ACK headers.mid"); nonEmpty(headers["server-timestamp"], "ACK headers.server-timestamp");
  } else if (keys === "dt,mid,sid") {
    literal(headers.dt, "j", "delivery ACK headers.dt"); nonEmpty(headers.mid, "delivery ACK headers.mid"); nonEmpty(headers.sid, "delivery ACK headers.sid");
  } else throw new Error("ACK headers are not a confirmed variant");
  return { kind: "ACK" };
}

function decodeSessionSignal(payload: RecordValue): XianyuInboundEvent {
  exactKeys(payload, ["1"], "session signal");
  const entries = requireArray(payload["1"], "session signal entries");
  if (entries.length !== 1) throw new Error("session signal entries must contain exactly one entry");
  const signal = requireRecord(entries[0], "session signal entry");
  exactKeys(signal, ["1", "2", "3", "4"], "session signal entry");
  const chatId = chat(signal["1"], "session signal chatId"); literal(signal["2"], 1, "session signal type");
  integerEnum(signal["3"], [0, 1], "session signal state"); goofishId(signal["4"], "session signal seller");
  return { kind: "SESSION_SIGNAL", chatId };
}

function decodePnm(payload: RecordValue): XianyuInboundEvent {
  if (Array.isArray(payload["1"])) {
    exactKeys(payload, ["1", "2", "3", "4", "5"], "PNM array frame"); literal(payload["2"], 2, "PNM array type");
    const messageIds = requireArray(payload["1"], "PNM array ids").map((id, index) => pnm(id, `PNM array ids[${index}]`));
    if (messageIds.length === 0) throw new Error("PNM array ids cannot be empty"); literal(payload["4"], 1, "PNM array state"); timestamp(payload["5"], "PNM array timestamp");
    return { kind: "PNM_STATUS", chatId: chat(payload["3"], "PNM array chat"), messageIds };
  }
  if (typeof payload["4"] === "string") {
    exactKeys(payload, ["1", "2", "3", "4", "5", "6"], "PNM scalar frame"); literal(payload["2"], 1, "PNM scalar type"); literal(payload["3"], 0, "PNM scalar state"); literal(payload["5"], 1, "PNM scalar flag"); timestamp(payload["6"], "PNM scalar timestamp");
    return { kind: "PNM_STATUS", chatId: chat(payload["4"], "PNM scalar chat"), messageIds: [pnm(payload["1"], "PNM scalar id")] };
  }
  exactKeys(payload, ["1", "2", "3", "4"], "PNM session frame"); literal(payload["2"], 1, "PNM session type"); timestamp(payload["4"], "PNM session timestamp");
  return { kind: "PNM_STATUS", chatId: chat(payload["1"], "PNM session chat"), messageIds: [pnm(payload["3"], "PNM session id")] };
}

function decodeOrderContext(payload: RecordValue): XianyuInboundEvent {
  exactKeys(payload, ["1", "2", "3", "4"], "order context"); literal(payload["2"], 1, "order context type"); timestamp(payload["4"], "order context timestamp");
  const details = requireRecord(payload["3"], "order context details");
  const buyerUserId = id(details.extUserId, "order context buyer"); const sellerUserId = id(details.itemSellerId, "order context seller");
  exactKeys(details, ["extUserId", "extUserType", "itemFeatures", "itemId", "itemMainPic", "itemSellerId", "itemTitle", "orderId", "ownerUserId", "ownerUserType", `squadId_${sellerUserId}`, `squadId_${buyerUserId}`, `squadName_${sellerUserId}`, `squadName_${buyerUserId}`], "order context details");
  literal(details.extUserType, "0", "order context extUserType"); const itemId = id(details.itemId, "order context itemId"); const orderId = id(details.orderId, "order context orderId");
  literal(details.ownerUserId, sellerUserId, "order context owner"); literal(details.ownerUserType, "0", "order context owner type"); httpUrl(details.itemMainPic, "order context itemMainPic"); nonEmpty(details.itemTitle, "order context itemTitle");
  const features = jsonRecord(details.itemFeatures, "order context itemFeatures"); exactKeys(features, ["idle_cat_leaf"], "order context itemFeatures"); const leaf = id(features.idle_cat_leaf, "order context idle_cat_leaf");
  literal(details[`squadId_${sellerUserId}`], itemId, "order context seller squad"); literal(details[`squadId_${buyerUserId}`], leaf, "order context buyer squad"); nonEmpty(details[`squadName_${sellerUserId}`], "order context seller squad name"); nonEmpty(details[`squadName_${buyerUserId}`], "order context buyer squad name");
  return { kind: "ORDER_CONTEXT", chatId: chat(payload["1"], "order context chat"), orderId, itemId, buyerUserId };
}

function decodeSummary(payload: RecordValue): XianyuInboundEvent {
  exactKeys(payload, ["1", "2", "3", "4"], "payment summary"); literal(payload["2"], 1, "payment summary type"); timestamp(payload["4"], "payment summary timestamp");
  const details = requireRecord(payload["3"], "payment summary details"); exactKeys(details, ["redReminder", "redReminderStyle"], "payment summary details"); literal(details.redReminderStyle, "1", "payment summary style"); const chatId = chat(payload["1"], "payment summary chat");
  if (details.redReminder === "等待卖家发货") return { kind: "PAYMENT_SUMMARY", chatId, redReminder: "等待卖家发货" };
  if (details.redReminder === "等待买家付款") return { kind: "WAITING_PAYMENT_SUMMARY", chatId, redReminder: "等待买家付款" };
  throw new Error("payment summary redReminder is unknown");
}

function decodeMessageUpdate(payload: RecordValue): XianyuInboundEvent {
  exactKeys(payload, ["1", "2", "3", "4", "5"], "message update"); pnm(payload["1"], "message update PNM"); literal(payload["3"], 1, "message update type"); timestamp(payload["5"], "message update timestamp"); const chatId = chat(payload["2"], "message update chat");
  const metadata = requireRecord(payload["4"], "message update metadata"); exactKeys(metadata, ["_CONTENT_MAP_UPDATE_PRE_dxCard.item.main.exContent.button", ...cardMetadataBase], "message update metadata");
  const button = jsonRecord(metadata["_CONTENT_MAP_UPDATE_PRE_dxCard.item.main.exContent.button"], "message update button"); exactKeys(button, ["bgColor", "borderColor", "fontColor", "targetUrl", "text"], "message update button"); literal(button.text, "已付款", "message update button text"); const buttonUrl = url(button.targetUrl, "message update button URL");
  booleanString(metadata.closePushReceiver, "message update closePushReceiver"); booleanString(metadata.closeUnreadNumber, "message update closeUnreadNumber"); booleanString(metadata.updateHead, "message update updateHead"); literal(metadata.detailNotice, "[我已修改价格，等待你付款]", "message update detailNotice"); literal(metadata.reminderContent, "[我已付款，等待你发货]", "message update reminderContent"); literal(metadata.reminderNotice, "我已修改价格，快来付款吧", "message update reminderNotice"); literal(metadata.reminderTitle, "交易消息", "message update reminderTitle"); literal(metadata.redReminder, "等待卖家发货", "message update redReminder"); literal(metadata.redReminderStyle, "1", "message update redReminderStyle"); const senderId = id(metadata.senderUserId, "message update sender"); literal(metadata.senderUserType, "0", "message update sender type"); literal(metadata.sessionType, "1", "message update session type"); id(metadata.receiver, "message update receiver"); const tag = taskTag(metadata.bizTag, "message update bizTag"); const reminder = reminderUrl(metadata.reminderUrl, chatId, "message update reminderUrl"); literal(reminder.peerUserId, senderId, "message update reminder peer"); const ext = jsonRecord(metadata.extJson, "message update extJson"); exactKeys(ext, ["msgArgs", "quickReply", "msgArg1", "updateKey", "messageId", "multiChannel", "contentType"], "message update extJson"); literal(ext.quickReply, "1", "message update quickReply"); literal(ext.msgArg1, "MsgCard", "message update msgArg1"); literal(ext.contentType, "26", "message update contentType"); const messageId = id(ext.messageId, "message update messageId"); literal(reminder.messageId, messageId, "message update reminder message"); const args = taskMessageArgs(ext.msgArgs, "message update msgArgs"); literal(args.taskId, tag.taskId, "message update task"); literal(args.messageId, messageId, "message update args message"); multiChannel(ext.multiChannel, "message update multiChannel");
  const update = ext.updateKey; const parts = id(update, "message update updateKey").split(":");
  if (parts.length !== 5 || parts[0] !== chatId || parts[2] !== "2" || parts[3] !== "TRADE_MODIFY_FEE_BUYER" || parts[4] !== "26") throw new Error("message update updateKey is invalid");
  const orderId = id(parts[1], "message update order"); literal(buttonUrl.searchParams.get("id"), orderId, "message update button order"); return { kind: "MESSAGE_UPDATE", chatId, messageId, orderId, updateType: "TRADE_MODIFY_FEE_BUYER" };
}

function decodeStandard(payload: RecordValue): XianyuInboundEvent {
  exactKeys(payload, ["1", "3"], "standard message payload"); const push = requireRecord(payload["3"], "standard message push"); exactKeys(push, ["needPush"], "standard message push"); stringEnum(push.needPush, ["true", "false"], "standard message needPush");
  const envelope = requireRecord(payload["1"], "standard message envelope"); exactKeys(envelope, ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "12"], "standard message envelope");
  const sender = requireRecord(envelope["1"], "standard message sender"); exactKeys(sender, ["1"], "standard message sender"); const senderId = bareGoofish(sender["1"], "standard message sender"); const chatId = chat(envelope["2"], "standard message chat"); pnm(envelope["3"], "standard message PNM"); literal(envelope["4"], 0, "standard message field 4"); timestamp(envelope["5"], "standard message timestamp"); literal(envelope["8"], 1, "standard message field 8"); literal(envelope["12"], 1, "standard message field 12");
  const content = requireRecord(envelope["6"], "standard message content"); exactKeys(content, ["1", "3"], "standard message content"); literal(content["1"], 101, "standard message content code"); const custom = requireRecord(content["3"], "standard message custom"); exactKeys(custom, ["1", "2", "3", "4", "5"], "standard message custom"); literal(custom["1"], "", "standard message custom 1"); literal(custom["3"], "", "standard message custom 3"); const display = nonEmpty(custom["2"], "standard message display"); const outerType = integer(custom["4"], "standard message outer contentType"); const inner = jsonRecord(custom["5"], "standard message inner"); const innerType = integer(inner.contentType, "standard message inner contentType"); if (outerType !== innerType) throw new Error("standard message content types conflict");
  const metadata = requireRecord(envelope["10"], "standard message metadata");
  if (outerType === 1 || outerType === 2) { literal(push.needPush, "true", "ordinary needPush"); literal(envelope["7"], 2, "ordinary envelope field 7"); literal(envelope["9"], 0, "ordinary envelope field 9"); const identity = decodeOrdinaryMetadata(metadata, senderId, chatId, display); return decodeOrdinary(inner, outerType, identity, display); }
  if (outerType === 26) { literal(push.needPush, "true", "card needPush"); literal(envelope["7"], 1, "card envelope field 7"); literal(envelope["9"], 0, "card envelope field 9"); return decodeCard(inner, metadata, { chatId, senderId, display }); }
  if (outerType === 14) { literal(push.needPush, "false", "tip needPush"); literal(envelope["7"], 1, "tip envelope field 7"); literal(envelope["9"], 1, "tip envelope field 9"); return decodeTip(inner, metadata, { chatId, senderId, display }); }
  throw new Error("unknown xianyu payload shape");
}

function decodeOrdinaryMetadata(metadata: RecordValue, senderId: string, chatId: string, display: string): Identity {
  exactKeys(metadata, ordinaryMetadataKeys, "ordinary metadata"); nonEmpty(metadata._appVersion, "ordinary app version"); literal(metadata._platform, "android", "ordinary platform"); nonEmpty(metadata.clientIp, "ordinary client IP"); nonEmpty(metadata.port, "ordinary port"); nonEmpty(metadata.umid, "ordinary UMID"); nonEmpty(metadata.umidToken, "ordinary UMID token"); nonEmpty(metadata.utdid, "ordinary UTDID"); literal(metadata.detailNotice, display, "ordinary detailNotice"); literal(metadata.reminderContent, display, "ordinary reminderContent"); nonEmpty(metadata.reminderNotice, "ordinary reminderNotice"); nonEmpty(metadata.reminderTitle, "ordinary reminderTitle"); literal(metadata.senderUserId, senderId, "ordinary sender"); literal(metadata.senderUserType, "0", "ordinary sender type"); literal(metadata.sessionType, "1", "ordinary session type");
  const ext = jsonRecord(metadata.extJson, "ordinary extJson"); exactKeys(ext, ["quickReply", "utdid", "messageId", "umidToken", "tag"], "ordinary extJson"); literal(ext.quickReply, "1", "ordinary quickReply"); literal(ext.tag, "u", "ordinary ext tag"); const messageId = id(ext.messageId, "ordinary extJson.messageId"); literal(ext.utdid, metadata.utdid, "ordinary ext utdid"); literal(ext.umidToken, metadata.umidToken, "ordinary ext token"); const tag = jsonRecord(metadata.bizTag, "ordinary bizTag"); exactKeys(tag, ["sourceId", "messageId"], "ordinary bizTag"); literal(tag.sourceId, "S:1", "ordinary bizTag source"); literal(tag.messageId, messageId, "ordinary bizTag.messageId"); const reminder = reminderUrl(metadata.reminderUrl, chatId, "ordinary reminderUrl"); literal(reminder.messageId, messageId, "ordinary reminder messageId"); literal(reminder.peerUserId, senderId, "ordinary reminder peer"); return { chatId, messageId, senderId, itemId: reminder.itemId };
}

function decodeOrdinary(inner: RecordValue, type: number, identity: Identity, display: string): XianyuInboundEvent {
  if (type === 1) { exactKeys(inner, ["atUsers", "contentType", "text"], "text inner"); emptyArray(inner.atUsers, "text atUsers"); literal(inner.contentType, 1, "text contentType"); const text = requireRecord(inner.text, "text body"); exactKeys(text, ["text"], "text body"); const value = nonEmpty(text.text, "text value"); literal(value, display, "text display"); return { kind: "TEXT_MESSAGE", ...identity, text: value }; }
  if (type === 2) { exactKeys(inner, ["atUsers", "contentType", "image"], "image inner"); emptyArray(inner.atUsers, "image atUsers"); literal(inner.contentType, 2, "image contentType"); const image = requireRecord(inner.image, "image body"); exactKeys(image, ["pics"], "image body"); const pics = requireArray(image.pics, "image pics"); if (pics.length !== 1) throw new Error("image pics must contain exactly one value"); const pic = requireRecord(pics[0], "image pic"); exactKeys(pic, ["height", "type", "url", "width"], "image pic"); positive(pic.height, "image height"); literal(pic.type, 0, "image type"); const imageUrl = httpsUrl(pic.url, "image URL"); positive(pic.width, "image width"); return { kind: "IMAGE_MESSAGE", ...identity, imageUrl }; }
  throw new Error("unknown xianyu payload shape");
}

function decodeCard(inner: RecordValue, metadata: RecordValue, base: { chatId: string; senderId: string; display: string }): XianyuInboundEvent {
  exactKeys(inner, ["contentType", "dxCard"], "trade card inner"); literal(inner.contentType, 26, "trade card contentType"); const card = requireRecord(inner.dxCard, "trade card dxCard"); exactKeys(card, ["item", "template"], "trade card dxCard"); const item = requireRecord(card.item, "trade card item"); exactKeys(item, ["main"], "trade card item"); const main = requireRecord(item.main, "trade card main"); exactKeys(main, ["clickParam", "exContent", "targetUrl"], "trade card main"); const click = requireRecord(main.clickParam, "trade card clickParam"); exactKeys(click, ["arg1", "args"], "trade card clickParam"); literal(click.arg1, "MsgCard", "trade card clickParam arg1"); const clickArgs = taskMessageArgs(click.args, "trade card clickParam args");
  const content = requireRecord(main.exContent, "trade card exContent"); exactKeys(content, ["bgColor", "button", "desc", "descColor", "title", "upgrade"], "trade card exContent"); nonEmpty(content.bgColor, "trade card bgColor"); nonEmpty(content.desc, "trade card desc"); nonEmpty(content.descColor, "trade card descColor"); const title = nonEmpty(content.title, "trade card title"); const paid = title === "我已付款，等待你发货"; const waiting = title === "我已拍下，待付款"; if (!paid && !waiting) throw new Error("trade card title is unknown"); literal(base.display, `[${title}]`, "trade card display"); const upgrade = requireRecord(content.upgrade, "trade card upgrade"); exactKeys(upgrade, ["targetUrl", "version"], "trade card upgrade"); url(upgrade.targetUrl, "trade card upgrade URL"); nonEmpty(upgrade.version, "trade card upgrade version"); const template = requireRecord(card.template, "trade card template"); exactKeys(template, ["name", "url", "version"], "trade card template"); nonEmpty(template.name, "trade card template name"); url(template.url, "trade card template URL"); nonEmpty(template.version, "trade card template version");
  const physical = paid && Object.hasOwn(metadata, "csReception"); const common = decodeCardMetadata(metadata, base.chatId, base.senderId, waiting || physical, waiting || physical, paid ? "等待卖家发货" : "等待买家付款"); literal(clickArgs.taskId, common.taskId, "trade card click task"); literal(clickArgs.messageId, common.messageId, "trade card click message");
  const button = requireRecord(content.button, "trade card button"); exactKeys(button, ["bgColor", "borderColor", "clickParam", "fontColor", "targetUrl", "text"], "trade card button"); nonEmpty(button.bgColor, "trade card button bgColor"); nonEmpty(button.borderColor, "trade card button borderColor"); nonEmpty(button.fontColor, "trade card button fontColor"); const buttonText = nonEmpty(button.text, "trade card button text"); const buttonClick = requireRecord(button.clickParam, "trade card button clickParam"); exactKeys(buttonClick, ["arg1", "args"], "trade card button clickParam"); literal(buttonClick.arg1, "MsgCardAction", "trade card button arg1"); const buttonArgs = requireRecord(buttonClick.args, "trade card button args"); exactKeys(buttonArgs, ["task_id", "source", "button_text", "msg_id"], "trade card button args"); literal(buttonArgs.source, "im", "trade card button source"); literal(buttonArgs.task_id, common.taskId, "trade card button task"); literal(buttonArgs.msg_id, common.messageId, "trade card button message"); literal(buttonArgs.button_text, buttonText, "trade card button text relation"); const mainUrl = url(main.targetUrl, "trade card main URL"); literal(mainUrl.protocol, "fleamarket:", "trade card main protocol"); literal(mainUrl.hostname, "order_detail", "trade card main host"); literal(mainUrl.pathname, "", "trade card main path"); literal(mainUrl.hash, "", "trade card main fragment"); exactQuery(mainUrl, { id: "", role: "" }, "trade card main query"); const mainOrderId = id(mainUrl.searchParams.get("id"), "trade card main order"); const buttonUrl = url(button.targetUrl, "trade card button URL");
  if (waiting) { literal(mainUrl.searchParams.get("role"), "seller", "waiting card role"); literal(buttonUrl.protocol, "fleamarket:", "waiting card button protocol"); literal(buttonUrl.hostname, "adjust_price", "waiting card button host"); literal(buttonUrl.pathname, "", "waiting card button path"); literal(buttonUrl.hash, "", "waiting card button fragment"); exactQuery(buttonUrl, { flutter: "true", bizOrderId: "" }, "waiting card button query"); const orderId = id(buttonUrl.searchParams.get("bizOrderId"), "waiting card button order"); literal(mainOrderId, orderId, "waiting card order relation"); literal(common.extJson.updateKey, `${base.chatId}:${orderId}:1_not_pay_seller`, "waiting card updateKey"); return { kind: "WAITING_PAYMENT_CARD", chatId: common.chatId, messageId: common.messageId, senderId: common.senderId, itemId: common.itemId, orderId }; }
  literal(mainUrl.searchParams.get("role"), "Seller", "paid card role"); literal(buttonUrl.protocol, "https:", "paid card button protocol"); const expectedPath = physical ? "/wow/moyu/moyu-project/idle-logistics/pages/idleDeliver" : "/wow/moyu/moyu-project/idle-logistics/pages/noPostageRequired"; literal(buttonUrl.pathname, expectedPath, "paid card button path"); literal(buttonUrl.hash, "", "paid card button fragment"); exactQuery(buttonUrl, physical ? { kun: "true", titleVisible: "false", useCusFont: "'true'", orderId: "" } : { kun: "true", opaque: "false", orderId: "" }, "paid card button query"); const orderId = id(buttonUrl.searchParams.get("orderId"), "paid card button order"); literal(mainOrderId, orderId, "paid card order relation"); const state = physical ? "63" : "64"; literal(common.extJson.updateKey, `${base.chatId}:${orderId}:${state}:TRADE_PAID_DONE_SELLER:26`, "paid card updateKey"); return { kind: "PAID_CARD", chatId: common.chatId, messageId: common.messageId, senderId: common.senderId, itemId: common.itemId, orderId };
}

function decodeCardMetadata(metadata: RecordValue, chatId: string, senderId: string, hasCsReception: boolean, hasCorrelation: boolean, redReminder: string): CommonMetadata {
  const expected = [...cardMetadataBase]; if (hasCsReception) expected.push("csReception"); exactKeys(metadata, expected, "card metadata"); booleanString(metadata.closePushReceiver, "card closePushReceiver"); booleanString(metadata.closeUnreadNumber, "card closeUnreadNumber"); if (hasCsReception) booleanString(metadata.csReception, "card csReception"); booleanString(metadata.updateHead, "card updateHead"); literal(metadata.redReminder, redReminder, "card redReminder"); literal(metadata.redReminderStyle, "1", "card redReminderStyle"); literal(metadata.senderUserId, senderId, "card sender"); literal(metadata.senderUserType, "0", "card sender type"); literal(metadata.sessionType, "1", "card session type"); const display = redReminder === "等待买家付款" ? "我已拍下，待付款" : "我已付款，等待你发货"; literal(metadata.detailNotice, `[${display}]`, "card detailNotice"); literal(metadata.reminderContent, `[${display}]`, "card reminderContent"); nonEmpty(metadata.reminderNotice, "card reminderNotice"); nonEmpty(metadata.reminderTitle, "card reminderTitle"); const tag = taskTag(metadata.bizTag, "card bizTag"); const reminder = reminderUrl(metadata.reminderUrl, chatId, "card reminderUrl"); id(metadata.receiver, "card receiver"); literal(reminder.peerUserId, senderId, "card reminder peer"); const ext = jsonRecord(metadata.extJson, "card extJson"); const extKeys = ["msgArgs", "quickReply", "msgArg1", "updateKey", "messageId", "multiChannel", "contentType"]; if (hasCorrelation) extKeys.push("correlationGroupId"); exactKeys(ext, extKeys, "card extJson"); literal(ext.quickReply, "1", "card quickReply"); literal(ext.msgArg1, "MsgCard", "card msgArg1"); literal(ext.contentType, "26", "card contentType"); const messageId = id(ext.messageId, "card messageId"); literal(reminder.messageId, messageId, "card reminder message"); const args = taskMessageArgs(ext.msgArgs, "card msgArgs"); literal(args.taskId, tag.taskId, "card task relation"); literal(args.messageId, messageId, "card message relation"); multiChannel(ext.multiChannel, "card multiChannel"); if (hasCorrelation) id(ext.correlationGroupId, "card correlationGroupId"); return { chatId, messageId, senderId, itemId: reminder.itemId, taskId: tag.taskId, extJson: ext };
}

function decodeTip(inner: RecordValue, metadata: RecordValue, base: { chatId: string; senderId: string; display: string }): XianyuInboundEvent {
  exactKeys(inner, ["contentType", "tip"], "tip inner"); literal(inner.contentType, 14, "tip contentType"); const tip = requireRecord(inner.tip, "tip body"); exactKeys(tip, ["action", "tip"], "tip body"); literal(tip.tip, base.display, "tip display"); const action = requireRecord(tip.action, "tip action"); exactKeys(action, ["actionType", "page"], "tip action"); literal(action.actionType, 4, "tip actionType"); const page = requireRecord(action.page, "tip page"); exactKeys(page, ["actionName", "actionStyle", "actionType", "iosActionStyle", "showGuideAlways", "url", "utName", "utParams"], "tip page"); nonEmpty(page.actionName, "tip actionName"); literal(page.actionStyle, 0, "tip actionStyle"); literal(page.actionType, 4, "tip page actionType"); literal(page.iosActionStyle, 0, "tip iosActionStyle"); literal(page.showGuideAlways, false, "tip showGuideAlways"); const tipUrl = url(page.url, "tip URL"); literal(tipUrl.protocol, "fleamarket:", "tip URL protocol"); literal(tipUrl.hostname, "item", "tip URL host"); literal(tipUrl.pathname, "", "tip URL path"); literal(tipUrl.hash, "", "tip URL fragment"); exactQuery(tipUrl, { id: "" }, "tip URL query"); literal(page.utName, "MsgTips", "tip utName"); const pageArgs = taskMessageArgs(page.utParams, "tip utParams"); exactKeys(metadata, tipMetadataKeys, "tip metadata"); booleanString(metadata.closePushReceiver, "tip closePushReceiver"); booleanString(metadata.closeUnreadNumber, "tip closeUnreadNumber"); booleanString(metadata.updateHead, "tip updateHead"); literal(metadata.detailNotice, base.display, "tip detailNotice"); literal(metadata.reminderContent, base.display, "tip reminderContent"); literal(metadata.senderUserId, base.senderId, "tip sender"); literal(metadata.senderUserType, "0", "tip sender type"); literal(metadata.sessionType, "1", "tip session type"); const tag = taskTag(metadata.bizTag, "tip bizTag"); const reminder = reminderUrl(metadata.reminderUrl, base.chatId, "tip reminderUrl"); literal(tipUrl.searchParams.get("id"), reminder.itemId, "tip URL item"); id(metadata.receiver, "tip receiver"); literal(reminder.peerUserId, base.senderId, "tip reminder peer"); const ext = jsonRecord(metadata.extJson, "tip extJson"); exactKeys(ext, ["msgArgs", "msgArg1", "messageId", "contentType"], "tip extJson"); literal(ext.msgArg1, "MsgTips", "tip msgArg1"); literal(ext.contentType, "14", "tip contentType"); const messageId = id(ext.messageId, "tip messageId"); literal(reminder.messageId, messageId, "tip reminder message"); const extArgs = taskMessageArgs(ext.msgArgs, "tip msgArgs"); literal(pageArgs.taskId, tag.taskId, "tip task"); literal(extArgs.taskId, tag.taskId, "tip ext task"); literal(pageArgs.messageId, messageId, "tip page message"); literal(extArgs.messageId, messageId, "tip ext message"); return { kind: "IGNORED_TIP_MESSAGE", chatId: base.chatId, messageId };
}

function taskTag(value: unknown, context: string): { taskId: string } { const tag = jsonRecord(value, context); exactKeys(tag, taskTagKeys, context); const taskId = id(tag.taskId, `${context}.taskId`); literal(tag.materialId, taskId, `${context}.materialId`); literal(tag.sourceId, `C2C:${taskId}`, `${context}.sourceId`); nonEmpty(tag.taskName, `${context}.taskName`); return { taskId }; }
function taskMessageArgs(value: unknown, context: string): { taskId: string; messageId: string } { const args = requireRecord(value, context); exactKeys(args, ["task_id", "source", "msg_id"], context); literal(args.source, "im", `${context}.source`); return { taskId: id(args.task_id, `${context}.task_id`), messageId: id(args.msg_id, `${context}.msg_id`) }; }
function multiChannel(value: unknown, context: string): void { const channel = requireRecord(value, context); exactKeys(channel, multiChannelKeys, context); const expected: Record<string, string> = { huawei: "EXPRESS", xiaomi: "108000", oppo_notify_level: "16", honor: "NORMAL", agoo: "product", oppo_category: "ORDER", vivo: "ORDER" }; for (const key of multiChannelKeys) literal(channel[key], expected[key], `${context}.${key}`); }
function reminderUrl(value: unknown, chatId: string, context: string): { itemId: string; messageId: string; peerUserId: string } { const parsed = url(value, context); literal(parsed.protocol, "fleamarket:", `${context} protocol`); literal(parsed.hostname, "message_chat", `${context} host`); literal(parsed.pathname, "", `${context} path`); literal(parsed.hash, "", `${context} fragment`); const actual: string[] = []; parsed.searchParams.forEach((_, key) => actual.push(key)); actual.sort(); const expected = ["adv", "itemId", "messageId", "peerUserId", "sid"]; if (actual.length !== expected.length || actual.some((key, index) => key !== expected[index])) throw new Error(`${context} has unexpected query keys`); literal(parsed.searchParams.get("adv"), "no", `${context} adv`); literal(parsed.searchParams.get("sid"), chatId, `${context} sid`); return { itemId: id(parsed.searchParams.get("itemId"), `${context} itemId`), messageId: id(parsed.searchParams.get("messageId"), `${context} messageId`), peerUserId: id(parsed.searchParams.get("peerUserId"), `${context} peerUserId`) }; }
function exactQuery(parsed: URL, expected: Record<string, string>, context: string): void { const keys: string[] = []; parsed.searchParams.forEach((_, key) => keys.push(key)); keys.sort(); const expectedKeys = Object.keys(expected).sort(); if (keys.length !== expectedKeys.length || keys.some((key, index) => key !== expectedKeys[index])) throw new Error(`${context} has unexpected query keys`); for (const key of expectedKeys) { const value = parsed.searchParams.get(key); if (expected[key] === "") id(value, `${context}.${key}`); else literal(value, expected[key], `${context}.${key}`); } }

function isStandard(payload: RecordValue): boolean { return isRecord(payload["1"]) && isRecord(payload["3"]) && Object.hasOwn(payload["3"], "needPush"); }
function isMessageUpdate(payload: RecordValue): boolean { return isRecord(payload["4"]) && Object.hasOwn(payload["4"], "extJson"); }
function isPnm(payload: RecordValue): boolean { return Array.isArray(payload["1"]) || (typeof payload["1"] === "string" && (typeof payload["3"] === "string" || payload["3"] === 0)); }
function isOrderContext(payload: RecordValue): boolean { return isRecord(payload["3"]) && Object.hasOwn(payload["3"], "orderId"); }
function isSummary(payload: RecordValue): boolean { return isRecord(payload["3"]) && Object.hasOwn(payload["3"], "redReminder"); }

function exactKeys(value: RecordValue, expected: string[], context: string): void { const actual = Object.keys(value).sort(); const sorted = [...expected].sort(); if (actual.length !== sorted.length || actual.some((key, index) => key !== sorted[index])) throw new Error(`${context} has an unexpected structure`); }
function requireRecord(value: unknown, context: string): RecordValue { if (!isRecord(value)) throw new Error(`${context} must be an object`); return value; }
function isRecord(value: unknown): value is RecordValue { return typeof value === "object" && value !== null && !Array.isArray(value); }
function requireArray(value: unknown, context: string): unknown[] { if (!Array.isArray(value)) throw new Error(`${context} must be an array`); return value; }
function jsonRecord(value: unknown, context: string): RecordValue { const text = nonEmpty(value, context); try { return requireRecord(JSON.parse(text), context); } catch (error) { throw new Error(`${context} must be JSON object`, { cause: error }); } }
function nonEmpty(value: unknown, context: string): string { if (typeof value !== "string" || value.length === 0) throw new Error(`${context} must be a non-empty string`); return value; }
function id(value: unknown, context: string): string { const result = nonEmpty(value, context); if (result.includes("@")) throw new Error(`${context} must be bare ID`); return result; }
function chat(value: unknown, context: string): string { const raw = nonEmpty(value, context); if (!raw.endsWith("@goofish") || raw.length === 8) throw new Error(`${context} must have @goofish suffix`); return raw.slice(0, -8); }
function goofishId(value: unknown, context: string): string { const raw = nonEmpty(value, context); if (!raw.endsWith("@goofish") || raw.length === 8) throw new Error(`${context} must have @goofish suffix`); return raw; }
function bareGoofish(value: unknown, context: string): string { return chat(value, context); }
function pnm(value: unknown, context: string): string { const result = nonEmpty(value, context); if (!result.endsWith(".PNM")) throw new Error(`${context} must be PNM`); return result; }
function integer(value: unknown, context: string): number { if (typeof value !== "number" || !Number.isInteger(value)) throw new Error(`${context} must be integer`); return value; }
function positive(value: unknown, context: string): number { const result = integer(value, context); if (result <= 0) throw new Error(`${context} must be positive`); return result; }
function timestamp(value: unknown, context: string): void { positive(value, context); }
function integerEnum(value: unknown, allowed: number[], context: string): void { if (!allowed.includes(integer(value, context))) throw new Error(`${context} is not allowed`); }
function stringEnum(value: unknown, allowed: string[], context: string): void { if (!allowed.includes(nonEmpty(value, context))) throw new Error(`${context} is not allowed`); }
function booleanString(value: unknown, context: string): void { stringEnum(value, ["true", "false"], context); }
function emptyArray(value: unknown, context: string): void { if (!Array.isArray(value) || value.length !== 0) throw new Error(`${context} must be empty array`); }
function literal<T>(value: unknown, expected: T, context: string): asserts value is T { if (value !== expected) throw new Error(`${context} must equal ${String(expected)}`); }
function url(value: unknown, context: string): URL { try { return new URL(nonEmpty(value, context)); } catch (error) { throw new Error(`${context} must be URL`, { cause: error }); } }
function httpUrl(value: unknown, context: string): string { const parsed = url(value, context); if (parsed.protocol !== "http:" && parsed.protocol !== "https:") throw new Error(`${context} must be HTTP(S)`); return parsed.toString(); }
function httpsUrl(value: unknown, context: string): string { const parsed = url(value, context); if (parsed.protocol !== "https:") throw new Error(`${context} must be HTTPS`); return parsed.toString(); }
