<script setup lang="ts">
import { onMounted, ref } from "vue";
import { RefreshCw, ShieldCheck } from "lucide-vue-next";
import { ElMessage } from "element-plus";
import { api } from "../api";
import { formatDateTime } from "../format";
import type { AuditLog } from "../types";
import { decodeArray, decodeAuditLog } from "../contracts";
const rows = ref<AuditLog[]>([]); const loading = ref(false); const selected = ref<AuditLog | null>(null);
async function load() { loading.value = true; try { rows.value = await api("/api/v1/admin/audit-logs", {}, decodeArray(decodeAuditLog)); } catch (e) { ElMessage.error(e instanceof Error ? e.message : "加载失败"); } finally { loading.value = false; } }
onMounted(load);
</script>
<template><div class="page-stack"><div class="page-heading"><div><h1>操作审计</h1><p>最近 100 条授权、账号和敏感业务操作</p></div><el-button :icon="RefreshCw" circle title="刷新" @click="load" /></div><el-table v-loading="loading" :data="rows" class="desktop-data-table" empty-text="暂无审计记录" @row-click="selected=$event"><el-table-column label="时间" min-width="175"><template #default="{row}">{{ formatDateTime(row.createdAt) }}</template></el-table-column><el-table-column prop="actorUserId" label="操作用户" width="100" /><el-table-column prop="targetUserId" label="目标用户" width="100" /><el-table-column prop="action" label="动作" min-width="210" /><el-table-column label="资源" min-width="180"><template #default="{row}">{{ row.resourceType || '-' }} / {{ row.resourceId || '-' }}</template></el-table-column><el-table-column prop="ipAddress" label="IP" min-width="130" /></el-table><div v-loading="loading" class="mobile-data-list"><article v-for="row in rows" :key="row.id" class="mobile-data-card tappable" @click="selected=row"><div class="mobile-card-head"><div><span class="mobile-card-icon green"><ShieldCheck :size="18" /></span><div><strong>{{ row.action }}</strong><small>{{ formatDateTime(row.createdAt) }}</small></div></div><span class="muted">详情 ›</span></div><dl><div><dt>操作用户</dt><dd>{{ row.actorUserId || '-' }}</dd></div><div><dt>目标用户</dt><dd>{{ row.targetUserId || '-' }}</dd></div><div><dt>资源</dt><dd>{{ row.resourceType || '-' }} / {{ row.resourceId || '-' }}</dd></div><div><dt>来源 IP</dt><dd>{{ row.ipAddress || '-' }}</dd></div></dl></article><div v-if="!rows.length && !loading" class="mobile-empty"><ShieldCheck :size="24" /><span>暂无审计记录</span></div></div><el-drawer v-model="selected" title="审计详情" size="min(560px, 92vw)"><template v-if="selected"><dl class="detail-list"><div><dt>动作</dt><dd>{{ selected.action }}</dd></div><div><dt>资源</dt><dd>{{ selected.resourceType }} / {{ selected.resourceId }}</dd></div><div><dt>来源 IP</dt><dd>{{ selected.ipAddress || '-' }}</dd></div></dl><h3>变更前</h3><pre class="json-view">{{ selected.beforeJson || '-' }}</pre><h3>变更后</h3><pre class="json-view">{{ selected.afterJson || '-' }}</pre></template></el-drawer></div></template>
